{% set name = "omfit_classes" %}
{% set version = "3.2025.52.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11b51296e92f187ad1fed3f3ba8af94aa88cf8597b83b747d8ef6f63ce9a2f58

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - omfit_classes

about:
  home: https://omfit.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Classes of OMFIT (One Modeling Framework For Integrated Tasks)
  doc_url: https://omfit.io
  dev_url: https://github.com/gafusion/OMFIT-source

extra:
  recipe-maintainers:
    - smithsp
    - orso82
    - kalling
