{% set name = "omfit_classes" %}
{% set version = "3.2025.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c95e19a7edfa10516cc0ea2e9534d0578a7bbbad82dca17600dbb9088228b46

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - omfit_classes

about:
  home: https://omfit.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Classes of OMFIT (One Modeling Framework For Integrated Tasks)
  doc_url: https://omfit.io
  dev_url: https://github.com/gafusion/OMFIT-source

extra:
  recipe-maintainers:
    - smithsp
    - orso82
    - kalling
