{% set name = "omfit_classes" %}
{% set version = "3.2023.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f92e4db1622ceb5911ed54c444f29486146d6840f2309a21d131714bfff8626

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - omfit_classes

about:
  home: https://omfit.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Classes of OMFIT (One Modeling Framework For Integrated Tasks)
  doc_url: https://omfit.io
  dev_url: https://github.com/gafusion/OMFIT-source

extra:
  recipe-maintainers:
    - smithsp
    - orso82
    - kalling
