{% set name = "omfit_classes" %}
{% set version = "3.2024.39.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5721b5823a11de23a1a9a62f2e3573846c90cb96595de71790c3021268a49e5e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - omfit_classes

about:
  home: https://omfit.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Classes of OMFIT (One Modeling Framework For Integrated Tasks)
  doc_url: https://omfit.io
  dev_url: https://github.com/gafusion/OMFIT-source

extra:
  recipe-maintainers:
    - smithsp
    - orso82
    - kalling
